version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend

  todo-frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "5173"

  todo-backend:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/todo-app?authSource=admin
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
    ports:
      - "3456:27017"

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
